package commons

object Constants {

  val CSPRESOURCE_PREFIX = "resources__"

  val CSPRESOURCE_TYPE_FILE = "resources__file"

  val CSPRESOURCE_TYPE_REGEX = "resources__regex"

  val RULE_STATUS_TEST_PENDING = "TEST_PENDING"

  val RULE_STATUS_TEST_RUNNING = "TEST_RUNNING"

  val RULE_STATUS_TEST_SUCCESS = "TEST_SUCCESS"

  val RULE_STATUS_TEST_FAILED = "TEST_FAILED"

  val RULE_STATUS_PUBLISHED = "PUBLISHED"

  val RULE_STATUS_SUSPENDED = "SUSPENDED"
}
