#!/bin/sh
#
# HORTONWORKS DATAPLANE SERVICE AND ITS CONSTITUENT SERVICES
# (c) 2016-2018 Hortonworks, Inc. All rights reserved.
# This code is provided to you pursuant to your written agreement with Hortonworks, which may be the terms of the
# Affero General Public License version 3 (AGPLv3), or pursuant to a written agreement with a third party authorized
# to distribute this code.  If you do not have a written agreement with Hortonworks or with an authorized and
# properly licensed third party, you do not have any rights to this code.
# If this code is provided to you under the terms of the AGPLv3:
# (A) HORTONWORKS PROVIDES THIS CODE TO YOU WITHOUT WARRANTIES OF ANY KIND;
# (B) HORTONWORKS DISCLAIMS ANY AND ALL EXPRESS AND IMPLIED WARRANTIES WITH RESPECT TO THIS CODE, INCLUDING BUT NOT
# LIMITED TO IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE;
# (C) HORTONWORKS IS NOT LIABLE TO YOU, AND WILL NOT DEFEND, INDEMNIFY, OR HOLD YOU HARMLESS FOR ANY CLAIMS ARISING
# FROM OR RELATED TO THE CODE; AND
# (D) WITH RESPECT TO YOUR EXERCISE OF ANY RIGHTS GRANTED TO YOU FOR THE CODE, HORTONWORKS IS NOT LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES INCLUDING, BUT NOT LIMITED TO,
# DAMAGES RELATED TO LOST REVENUE, LOST PROFITS, LOSS OF INCOME, LOSS OF BUSINESS ADVANTAGE OR UNAVAILABILITY,
# OR LOSS OR CORRUPTION OF DATA.
#

if [ -z "$CONSUL_HOST" ]; then
    echo "Need to set CONSUL_HOST"
    exit 1
fi

DATABASE_ARGS=""
if [ -n "$DATABASE_URI" ]; then
    DATABASE_ARGS="$DATABASE_ARGS -Dslick.dbs.default.db.url=$DATABASE_URI"
fi

if [ -n "$DATABASE_USER" ]; then
    DATABASE_ARGS="$DATABASE_ARGS -Dslick.dbs.default.db.user=$DATABASE_USER"
fi

if [ -n "$DATABASE_PASS" ]; then
    DATABASE_ARGS="$DATABASE_ARGS -Dslick.dbs.default.db.password=$DATABASE_PASS"
fi

exec 2>&1
rm -f /usr/dss-app/RUNNING_PID && \
cd /usr/dss-app/bin && \
exec ./dss-app -DDSS_APP_HOME=${DSS_APP_HOME} \
               -Dconfig.resource=../conf/docker.conf \
               -Dplay.crypto.secret="129921029813" \
               -Dconsul.host=${CONSUL_HOST} \
               -Ddp.keystore.path=${KEYSTORE_PATH} \
               -Ddp.keystore.password=${KEYSTORE_PASSWORD} \
               $DATABASE_ARGS
